# fly.toml app configuration file generated for boba-sticker-v3-bondan-99 on 2026-05-04

app = "boba-sticker-v3-bondan-99"
primary_region = "sin"

[build]

[env]
  NODE_ENV = "production"
  PORT = "3000"
  PREFIX = "."

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

[mounts]
  source = "wa_auth_data"
  destination = "/data"

[[vm]]
  size = "shared-cpu-1x"
  memory = "256MB"
  cpus = 1
